<?php

namespace FrontBundle\Repository;

/**
 * PosicionesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PosicionesRepository extends \Doctrine\ORM\EntityRepository
{
}
